/**
 * Load bundled store catalog JSON (generated by scripts/mercadona-sync.mjs).
 */

/** @typedef {{ store: string, fetchedAt: string, productCount: number, products: import('./productMatcher.js').StoreProduct[] }} StoreCatalog */

let _cache = /** @type {Map<string, Promise<StoreCatalog>>} */ (new Map());

/**
 * @param {string} [store]
 * @returns {Promise<StoreCatalog>}
 */
export async function loadStoreCatalog(store = "mercadona") {
  const key = store.toLowerCase();
  if (!_cache.has(key)) {
    _cache.set(
      key,
      fetch(`/store/${key}.json`)
        .then((res) => {
          if (!res.ok) throw new Error(`Store catalog ${key}: HTTP ${res.status}`);
          return res.json();
        })
        .then((data) => {
          if (!data?.products?.length) throw new Error(`Store catalog ${key}: empty`);
          return data;
        }),
    );
  }
  return _cache.get(key);
}

/** @param {string} [store] */
export function resetStoreCatalogCache(store) {
  if (store) _cache.delete(store.toLowerCase());
  else _cache.clear();
}

export function isMercadonaStore(name) {
  return String(name ?? "").trim().toLowerCase() === "mercadona";
}
