-- Auto-generated by scripts/generate-supabase-seed.mjs — do not edit by hand.
-- RUN THIS FILE FIRST, on its own — paste it and click Run by itself, before
-- any of the seed_recipes_N_de_4.sql files. Idempotent, safe to re-run.

-- meal_role: migración 0001 solo creó los 5 originales; 0008 (desayuno/
-- merienda/postre) no siempre se aplicó; "salsa" no está en ninguna migración.
alter type meal_role add value if not exists 'cena';
alter type meal_role add value if not exists 'guarnicion';
alter type meal_role add value if not exists 'plato_unico';
alter type meal_role add value if not exists 'primero';
alter type meal_role add value if not exists 'segundo';
alter type meal_role add value if not exists 'desayuno';
alter type meal_role add value if not exists 'merienda';
alter type meal_role add value if not exists 'postre';
alter type meal_role add value if not exists 'salsa';

-- recipes: columnas de migraciones que este entorno puede no tener aplicadas
-- (se vio con product_aliases, de la 0008) — no toca las que ya existen.
alter table recipes add column if not exists name text;
alter table recipes add column if not exists category text;
alter table recipes add column if not exists main_protein text;
alter table recipes add column if not exists main_base text;
alter table recipes add column if not exists meal_roles meal_role[];
alter table recipes add column if not exists type text;
alter table recipes add column if not exists base_dish_id text;
alter table recipes add column if not exists required_appliance text;
alter table recipes add column if not exists time_minutes integer;
alter table recipes add column if not exists difficulty text;
alter table recipes add column if not exists season text;
alter table recipes add column if not exists kcal integer;
alter table recipes add column if not exists protein_g integer;
alter table recipes add column if not exists carbs_g integer;
alter table recipes add column if not exists fat_g integer;
alter table recipes add column if not exists base_servings integer;
alter table recipes add column if not exists kid_friendly boolean;
alter table recipes add column if not exists tupper_friendly boolean;
alter table recipes add column if not exists allergens text[];
alter table recipes add column if not exists ingredients jsonb;
alter table recipes add column if not exists steps text[];
alter table recipes add column if not exists description text;
alter table recipes add column if not exists methods jsonb;
alter table recipes add column if not exists product_aliases text[];
alter table recipes add column if not exists apetecible boolean;
alter table recipes add column if not exists montaje boolean;
alter table recipes add column if not exists can_be_garnish boolean;
alter table recipes add column if not exists main_ingredients text[];
alter table recipes add column if not exists sauce_id text;
