"""Process the Midjourney ingredient renders into public/ingredients/.

Midjourney names files like:
    u8146599693_<id>_cute_stylized_3D_cartoon_render_in_..._<uuid>_<n>.png

We pull <id> out of the prefix, centre-crop to square, downscale and quantize.
When several variants of the same id exist, the first one wins (sorted), so
re-running is deterministic.

Run: python scripts/make_ingredient_images.py
"""
import json
import re
from pathlib import Path

from PIL import Image

SRC = Path("Avatares/cards/ingredientes_recetas")
OUT = Path("public/ingredients")
SIZE = 200
COLORS = 128

# Everything between the Midjourney user prefix and the start of the prompt.
NAME_RE = re.compile(r"^u\d+_(.+?)_cute_stylized", re.IGNORECASE)


def square_crop(img):
    w, h = img.size
    s = min(w, h)
    return img.crop(((w - s) // 2, (h - s) // 2, (w - s) // 2 + s, (h - s) // 2 + s))


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    found = {}
    for src in sorted(SRC.glob("*.png")):
        m = NAME_RE.match(src.stem)
        if not m:
            continue
        ing = m.group(1).lower()
        # First variant wins; later duplicates (…_1, …_2, “(1)”) are skipped.
        found.setdefault(ing, src)

    for ing, src in sorted(found.items()):
        img = Image.open(src).convert("RGB")
        img = square_crop(img).resize((SIZE, SIZE), Image.LANCZOS)
        dst = OUT / f"{ing}.png"
        img.quantize(colors=COLORS, method=Image.MEDIANCUT).save(dst, optimize=True)

    # The resolver needs to know which ids actually shipped, so it can fall
    # back to a family/aisle image instead of requesting a 404.
    manifest = Path("src/lib/ingredientImageIds.js")
    ids = ",\n  ".join(json.dumps(i) for i in sorted(found))
    manifest.write_text(
        "// Generated by scripts/make_ingredient_images.py — do not edit by hand.\n"
        f"export const INGREDIENT_IMAGE_IDS = [\n  {ids},\n];\n",
        encoding="utf-8",
    )

    total_kb = sum((OUT / f"{i}.png").stat().st_size for i in found) // 1024
    print(f"{len(found)} ingredientes -> {OUT}  ({total_kb}KB total)")
    print(f"manifest -> {manifest}")


if __name__ == "__main__":
    main()
