// Batch-regenerate every "<carne|pescado> + patatas fritas" combo photo. The
// original batch rendered these as a yogurt/cucumber plate with no fries at all;
// buildPrompt now carries a hard "patatas fritas" disambiguation clause, so this
// re-runs the whole set through it. Meat/fish only — fries no longer pair with
// eggs/salads/pasta in pairGarnishes, so those combos are intentionally skipped.
//
// Usage:
//   node --env-file=.env.local scripts/regen-fritas.mjs

import { GoogleGenAI } from "@google/genai";
import { put } from "@vercel/blob";
import { writeFileSync, readFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { buildPrompt } from "./lib/combos.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const GEMINI_KEY = process.env.GEMINI_AI_STUDIO_KEY;
const BLOB_TOKEN = process.env.BLOB_READ_WRITE_TOKEN;
if (!GEMINI_KEY) { console.error("❌  GEMINI_AI_STUDIO_KEY no encontrado"); process.exit(1); }
if (!BLOB_TOKEN) { console.error("❌  BLOB_READ_WRITE_TOKEN no encontrado"); process.exit(1); }

const GARNISH_ID = "guarniciones_022";
const GARNISH_NAME = "patatas fritas";
// Already regenerated by hand as the pilot — skip to save a call.
const SKIP = new Set(["pescados_006"]);

// id → dish name for the two families fries pair with.
const nameById = {};
for (const fam of ["carnes", "pescados"]) {
  const recipes = JSON.parse(readFileSync(join(ROOT, "src", "data", "recipes", `${fam}.json`), "utf8"));
  for (const r of recipes) nameById[r.id] = r.name;
}

const MANIFEST = join(ROOT, "src", "assets", "dishes", "dishImages.json");
const manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));

const targets = Object.keys(manifest)
  .filter((k) => k.endsWith(`+${GARNISH_ID}`))
  .map((k) => k.slice(0, k.indexOf("+")))
  .filter((base) => /^(carnes|pescados)_\d+$/.test(base) && !SKIP.has(base));

console.log(`🎯  ${targets.length} combos de patatas fritas a regenerar\n`);

const ai = new GoogleGenAI({ apiKey: GEMINI_KEY });
const outDir = join(ROOT, "output", "dishes");
if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

const sleep = (ms) => new Promise((res) => setTimeout(res, ms));
let ok = 0;
const failed = [];

for (const base of targets) {
  const comboId = `${base}+${GARNISH_ID}`;
  const dishName = nameById[base];
  if (!dishName) { console.warn(`⚠️  Sin nombre para ${base}, salto`); failed.push(base); continue; }

  const prompt = buildPrompt({ combo_id: comboId, dish_name: dishName, garnish_name: GARNISH_NAME });
  try {
    const stream = await ai.models.generateContentStream({
      model: "gemini-2.5-flash-image",
      contents: [{ role: "user", parts: [{ text: prompt }] }],
      config: { responseModalities: ["IMAGE", "TEXT"], httpOptions: { timeout: 120000, headers: {} } },
    });
    let imgPart = null;
    for await (const chunk of stream) {
      for (const p of chunk?.candidates?.[0]?.content?.parts ?? []) {
        if (p.inlineData?.mimeType?.startsWith("image/")) imgPart = p;
      }
    }
    if (!imgPart) throw new Error("sin imagen");

    const buffer = Buffer.from(imgPart.inlineData.data, "base64");
    writeFileSync(join(outDir, `${comboId}.jpg`), buffer);

    const blob = await put(`dishes/${comboId}.jpg`, buffer, {
      access: "public",
      token: BLOB_TOKEN,
      contentType: "image/jpeg",
      addRandomSuffix: false,
      allowOverwrite: true,
    });

    const current = manifest[comboId] ?? blob.url;
    const [urlBase, query] = current.split("?");
    const prevV = query ? Number(new URLSearchParams(query).get("v")) || 1 : 1;
    manifest[comboId] = `${urlBase}?v=${prevV + 1}`;
    writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + "\n", "utf8");

    ok += 1;
    console.log(`✅  [${ok}/${targets.length}] ${dishName} con patatas fritas`);
  } catch (err) {
    failed.push(base);
    console.warn(`❌  ${base}: ${err.message}`);
  }
  await sleep(1200);
}

console.log(`\n✨  Hecho: ${ok} OK, ${failed.length} fallidos${failed.length ? ` → ${failed.join(", ")}` : ""}`);
